chat/urls.py
from django.urls import path

from .views import *

app_name = 'chat'
urlpatterns = [
    # {% url('chat:list') %}
    path('', chat_rooms_list_view, name='list'),
    # {% url('chat:list') pk %}
    path('<int:pk>/', chat_room_detail_view, name='detail')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls', namespace='chat'))
]

chat/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext as _
from model_utils.models import TimeStampedModel


class ChatRoom(TimeStampedModel):
    name = models.CharField(
        verbose_name=_('Chat room name'),
        max_length=255
    )

    users = models.ManyToManyField(
        verbose_name=_('Chat participants'),
        related_name='chats',
        to=settings.AUTH_USER_MODEL,
        blank=True
    )

    def __str__(self):
        if self.users.exists():
            return f'{self.name} ({self.users.count()})'
        return self.name

    class Meta:
        verbose_name = 'Chat room'
        verbose_name_plural = 'Chat rooms'


class Message(TimeStampedModel):
    author = models.ForeignKey(
        verbose_name=_('Author'),
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )

    text = models.TextField(
        verbose_name=_('Text')
    )

    chat = models.ForeignKey(
        verbose_name=_('Chat room'),
        to=ChatRoom,
        on_delete=models.CASCADE
    )

    def get_create_datetime(self):
        return self.created.strftime('%d.%m.%Y %H:%M:%S')

    def __str__(self):
        return f'Message from {self.author} to chat room {self.chat.name}'

    class Meta:
        default_related_name = 'messages'

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

chat/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView

from .models import ChatRoom

__all__ = ['chat_rooms_list_view', 'chat_room_detail_view']


class ChatRoomsListView(LoginRequiredMixin, ListView):
    queryset = ChatRoom.objects.all()
    template_name = 'chat/chat_rooms.html'
    context_object_name = 'chat_rooms'

chat_rooms_list_view = ChatRoomsListView.as_view()


class ChatRoomView(LoginRequiredMixin, DetailView):
    model = ChatRoom
    template_name = 'chat/chat.html'
    context_object_name = 'chat'

chat_room_detail_view = ChatRoomView.as_view()

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title %}Django Websocket Chat{% endblock title %}</title>
</head>

<body>
{% block css %}
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
{% endblock css %}

  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>

  {% block javascript %}
    <!-- Bootstrap JavaScript -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  {% endblock javascript %}

</body>
</html>

templates/chat/chat.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ block.super }} - {{ chat.name }}{% endblock title %}

{% block javascript %}
  <script src="{% static 'js/chat.js' %}"></script>
{% endblock %}

{% block content %}
  <div class="row" data-chat-room="{{ chat.id }}" data-user="{{ user }}">
    <div class="col messages">
      {% for message in chat.messages.all %}
        <div class="alert alert-primary msg" role="alert">
          <h6 class="alert-heading username">{{ message.author }}<span class="time" style="float: right">{{ message.get_create_datetime }}</span></h6>
          <hr>
          <p class="mb-0 text">{{ message.text }}</p>
        </div>
      {% endfor %}
    </div>
  </div>

  <nav class="navbar fixed-bottom navbar-light bg-light">
    <form class="mx-2 my-auto d-inline w-100">
      <div class="input-group">
      <input type="text" class="form-control" id="message-text">
        <span class="input-group-append">
          <button class="btn btn-outline-primary" id="message-submit" type="button">Submit</button>
        </span>
      </div>
    </form>
  </nav>

{% endblock content %}

templates/chat/chat_rooms.html
{% extends 'base.html' %}

{% block title %}{{ block.super }} - Chat Rooms{% endblock title %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="tab-content" id="nav-tabContent">
        {% for room in chat_rooms %}
          <a href="{% url 'chat:detail' room.pk %}" class="list-group-item d-flex justify-content-between align-items-center">
            {{ room.name }}
            <span class="badge badge-primary badge-pill">{{ room.users.count }}</span>
          </a>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock content %}